* *********************************************************
* *
* * 08/06/16             DATABASE.DBC             00:00:00
* *
* *********************************************************
* *
* * Description:
* * This program was automatically generated by GENDBC
* * Version 2.26.67
* *
* *********************************************************

lParameters tcLogFileName

Public _GenDBC_Error, _GenDBC_LogFileName 
IF EMPTY(tcLogFileName)
	_GenDBC_LogFileName = "CreateEmptyDbc.log"
ELSE
	_GenDBC_LogFileName = tcLogFileName
ENDIF


DisplayStatus([Creating database...])
CREATE DATABASE 'DATABASE.DBC'
DisplayStatus([Creating table CONTRIBUYENTES...])
MakeTable_CONTRIBUYENTES()
DisplayStatus([Creating table BIENES...])
MakeTable_BIENES()
DisplayStatus([Creating table PROPIETARIOS...])
MakeTable_PROPIETARIOS()
DisplayStatus([Creating table VEHICULOS...])
MakeTable_VEHICULOS()
DisplayStatus([Creating table MODELOS...])
MakeTable_MODELOS()
DisplayStatus([Creating table MARCAS...])
MakeTable_MARCAS()
DisplayStatus([Creating table COLORES...])
MakeTable_COLORES()
DisplayStatus([Creating table COMERCIOS...])
MakeTable_COMERCIOS()
DisplayStatus([Creating table INMUEBLES...])
MakeTable_INMUEBLES()
DisplayStatus([Creating table BARRIOS...])
MakeTable_BARRIOS()
DisplayStatus([Creating table ZONAS...])
MakeTable_ZONAS()
DisplayStatus([Creating table ESTADOS...])
MakeTable_ESTADOS()
DisplayStatus([Creating table IMPUESTOS...])
MakeTable_IMPUESTOS()
DisplayStatus([Creating table RECIBOS...])
MakeTable_RECIBOS()
DisplayStatus([Creating table PLANES_DE_PAGOS...])
MakeTable_PLANES_DE_PAGOS()
DisplayStatus([Creating table DETALLES_PLAN_DE_PAGOS...])
MakeTable_DETALLES_PLAN_DE_PAGOS()
DisplayStatus([Creating table IMPUESTOXPLAN_DE_PAGOS...])
MakeTable_IMPUESTOXPLAN_DE_PAGOS()
DisplayStatus([Creating table CALLES...])
MakeTable_CALLES()
DisplayStatus([Creating table LOCALIDADES...])
MakeTable_LOCALIDADES()
DisplayStatus([Creating table PARTNAC...])
MakeTable_PARTNAC()
DisplayStatus([Creating table DPTOS...])
MakeTable_DPTOS()
DisplayStatus([Creating table PROVINCIAS...])
MakeTable_PROVINCIAS()
DisplayStatus([Creating table TIPODOC...])
MakeTable_TIPODOC()
DisplayStatus([Creating persistent relations...])
MakeRelation_1()
MakeRelation_2()
MakeRelation_3()
MakeRelation_4()
MakeRelation_5()
MakeRelation_6()
MakeRelation_7()
MakeRelation_8()
MakeRelation_9()
MakeRelation_10()
MakeRelation_11()
MakeRelation_12()
MakeRelation_13()
MakeRelation_14()
MakeRelation_15()
MakeRelation_16()
DisplayStatus([Finished.])
RELEASE _GenDBC_LogFileName 

FUNCTION MakeTable_CONTRIBUYENTES
TRY 
***** Table setup for CONTRIBUYENTES *****
CREATE TABLE 'CONTRIBUYENTES.DBF' NAME 'CONTRIBUYENTES' (NRO_CONTRIBUYENTE I NOT NULL AUTOINC NEXTVALUE 6 STEP 1, ;
                             NOMBRE C(50) NOT NULL, ;
                             CUIT N(15, 0) NOT NULL, ;
                             DIRECCION_REAL C(60) NOT NULL, ;
                             DIRECCION_COMERCIAL C(60) NOT NULL, ;
                             TELEFONO C(30) NOT NULL, ;
                             CELULAR C(30) NOT NULL, ;
                             SEXO C(1) NOT NULL, ;
                             FECHA_NAC D NOT NULL, ;
                             TIPO_CONTRIB C(20) NOT NULL, ;
                             EMAIL C(50) NOT NULL)

***** Create each index for CONTRIBUYENTES *****
ALTER TABLE 'CONTRIBUYENTES' ADD PRIMARY KEY NRO_CONTRIBUYENTE TAG NRO_CONTRI COLLATE 'MACHINE'

***** Change properties for CONTRIBUYENTES *****
	STRTOFILE("Table ' CONTRIBUYENTES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' CONTRIBUYENTES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_BIENES
TRY 
***** Table setup for BIENES *****
CREATE TABLE 'BIENES.DBF' NAME 'BIENES' (ID_BIEN I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                     VALOR_BASE N(15, 10) NOT NULL)

***** Create each index for BIENES *****
ALTER TABLE 'BIENES' ADD PRIMARY KEY ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'

***** Change properties for BIENES *****
	STRTOFILE("Table ' BIENES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' BIENES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_PROPIETARIOS
TRY 
***** Table setup for PROPIETARIOS *****
CREATE TABLE 'PROPIETARIOS.DBF' NAME 'PROPIETARIOS' (ID_BIEN I NOT NULL, ;
                           NRO_CONTRIBUYENTE I NOT NULL, ;
                           FECHA_ALTA D NOT NULL, ;
                           FECHA_BAJA D NOT NULL)

***** Create each index for PROPIETARIOS *****
INDEX ON NRO_CONTRIBUYENTE TAG NRO_CONTRI COLLATE 'MACHINE'
INDEX ON ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'
ALTER TABLE 'PROPIETARIOS' ADD PRIMARY KEY STR(ID_BIEN)+STR(NRO_CONTRIBUYENTE)+DTOS(FECHA_ALTA) TAG NRO_PROP COLLATE 'MACHINE'

***** Change properties for PROPIETARIOS *****
	STRTOFILE("Table ' PROPIETARIOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' PROPIETARIOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_VEHICULOS
TRY 
***** Table setup for VEHICULOS *****
CREATE TABLE 'VEHICULOS.DBF' NAME 'VEHICULOS' (ID_BIEN C(10) NOT NULL, ;
                        DOMINIO C(15) NOT NULL, ;
                        ID_MARCA I NOT NULL, ;
                        ID_MODELO I NOT NULL, ;
                        COLOR C(40) NOT NULL, ;
                        TIPOVEHICULO C(30) NOT NULL, ;
                        NROMOTOR C(40) NOT NULL, ;
                        NROCHASIS C(40) NOT NULL, ;
                        REGISTROAUTOMO C(40) NOT NULL, ;
                        FECHA_ALTA D NOT NULL, ;
                        FECHA_BAJA D NOT NULL)

***** Create each index for VEHICULOS *****
INDEX ON ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'
ALTER TABLE 'VEHICULOS' ADD PRIMARY KEY DOMINIO TAG DOMINIO COLLATE 'MACHINE'
INDEX ON TIPOVEHICULO TAG TIPOVEHICU COLLATE 'MACHINE'
INDEX ON ID_MARCA TAG ID_MARCA COLLATE 'MACHINE'
INDEX ON ID_MODELO TAG ID_MODELO COLLATE 'MACHINE'

***** Change properties for VEHICULOS *****
	STRTOFILE("Table ' VEHICULOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' VEHICULOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_MODELOS
TRY 
***** Table setup for MODELOS *****
CREATE TABLE 'MODELOS.DBF' NAME 'MODELOS' (ID_MODELO I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                      DESCRIPCION C(45) NOT NULL, ;
                      ID_MARCA I NOT NULL)

***** Create each index for MODELOS *****
ALTER TABLE 'MODELOS' ADD PRIMARY KEY ID_MODELO TAG ID_MODELO COLLATE 'MACHINE'
INDEX ON ID_MARCA TAG ID_MARCA COLLATE 'MACHINE'

***** Change properties for MODELOS *****
	STRTOFILE("Table ' MODELOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' MODELOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_MARCAS
TRY 
***** Table setup for MARCAS *****
CREATE TABLE 'MARCAS.DBF' NAME 'MARCAS' (ID_MARCA I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                     DESCRIPCION C(45) NOT NULL)

***** Create each index for MARCAS *****
ALTER TABLE 'MARCAS' ADD PRIMARY KEY ID_MARCA TAG ID_MARCA COLLATE 'MACHINE'

***** Change properties for MARCAS *****
	STRTOFILE("Table ' MARCAS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' MARCAS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_COLORES
TRY 
***** Table setup for COLORES *****
CREATE TABLE 'COLORES.DBF' NAME 'COLORES' (ID_COLOR I NOT NULL AUTOINC NEXTVALUE 3 STEP 1, ;
                      DESCRIPCION C(10) NOT NULL)

***** Create each index for COLORES *****
ALTER TABLE 'COLORES' ADD PRIMARY KEY ID_COLOR TAG ID_COLOR COLLATE 'MACHINE'

***** Change properties for COLORES *****
	STRTOFILE("Table ' COLORES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' COLORES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_COMERCIOS
TRY 
***** Table setup for COMERCIOS *****
CREATE TABLE 'COMERCIOS.DBF' NAME 'COMERCIOS' (ID_COMERCIO I NOT NULL AUTOINC NEXTVALUE 2 STEP 1, ;
                        ID_BIEN I NOT NULL, ;
                        NOMBRE C(60) NOT NULL, ;
                        DIRECCION C(60) NOT NULL, ;
                        SUPERFICIE N(10, 0) NOT NULL, ;
                        BARRIO C(30) NOT NULL)

***** Create each index for COMERCIOS *****
ALTER TABLE 'COMERCIOS' ADD PRIMARY KEY ID_COMERCIO TAG ID_COMERCI COLLATE 'MACHINE'
INDEX ON ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'

***** Change properties for COMERCIOS *****
	STRTOFILE("Table ' COMERCIOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' COMERCIOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_INMUEBLES
TRY 
***** Table setup for INMUEBLES *****
CREATE TABLE 'INMUEBLES.DBF' NAME 'INMUEBLES' (CUENTA I NOT NULL, ;
                        ID_BIEN I NOT NULL, ;
                        COD_POSTAL C(20) NOT NULL, ;
                        BARRIO I NOT NULL, ;
                        DIRECCION C(60) NOT NULL, ;
                        NOM_CATASTRAL C(60) NOT NULL, ;
                        ESTADO C(30) NOT NULL, ;
                        BASEIMPONIBLE N(20, 2) NOT NULL)

***** Create each index for INMUEBLES *****
ALTER TABLE 'INMUEBLES' ADD PRIMARY KEY CUENTA TAG CUENTA COLLATE 'MACHINE'
INDEX ON ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'
INDEX ON BARRIO TAG BARRIO COLLATE 'MACHINE'
INDEX ON BASEIMPONIBLE TAG BASEIMPONI COLLATE 'MACHINE'
INDEX ON ESTADO TAG ESTADO COLLATE 'MACHINE'

***** Change properties for INMUEBLES *****
	STRTOFILE("Table ' INMUEBLES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' INMUEBLES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_BARRIOS
TRY 
***** Table setup for BARRIOS *****
CREATE TABLE 'BARRIOS.DBF' NAME 'BARRIOS' (ID_BARRIO I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                      DESCRIPCION C(45) NOT NULL, ;
                      ID_ZONA I NOT NULL)

***** Create each index for BARRIOS *****
ALTER TABLE 'BARRIOS' ADD PRIMARY KEY ID_BARRIO TAG ID_BARRIO COLLATE 'MACHINE'
INDEX ON ID_ZONA TAG ID_ZONA COLLATE 'MACHINE'

***** Change properties for BARRIOS *****
	STRTOFILE("Table ' BARRIOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' BARRIOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_ZONAS
TRY 
***** Table setup for ZONAS *****
CREATE TABLE 'ZONAS.DBF' NAME 'ZONAS' (ID_ZONA I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                    DESCRIPCION C(45) NOT NULL)

***** Create each index for ZONAS *****
ALTER TABLE 'ZONAS' ADD PRIMARY KEY ID_ZONA TAG ID_ZONA COLLATE 'MACHINE'

***** Change properties for ZONAS *****
	STRTOFILE("Table ' ZONAS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' ZONAS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_ESTADOS
TRY 
***** Table setup for ESTADOS *****
CREATE TABLE 'ESTADOS.DBF' NAME 'ESTADOS' (ID_ESTADO I NOT NULL AUTOINC NEXTVALUE 6 STEP 1, ;
                      DESCRIPCION C(45) NOT NULL)

***** Create each index for ESTADOS *****
ALTER TABLE 'ESTADOS' ADD PRIMARY KEY ID_ESTADO TAG ID_ESTADO COLLATE 'MACHINE'

***** Change properties for ESTADOS *****
	STRTOFILE("Table ' ESTADOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' ESTADOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_IMPUESTOS
TRY 
***** Table setup for IMPUESTOS *****
CREATE TABLE 'IMPUESTOS.DBF' NAME 'IMPUESTOS' (ID_IMPUESTO I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                        NRO_CONTRIBUYENTE I NOT NULL, ;
                        ID_BIEN I NOT NULL, ;
                        FECHA_GENERACION T NOT NULL, ;
                        MONTO N(10, 4) NOT NULL, ;
                        FECHA_VENCIMIENTO T NOT NULL, ;
                        INTERES I NOT NULL, ;
                        RECIBO I NULL)

***** Create each index for IMPUESTOS *****
ALTER TABLE 'IMPUESTOS' ADD PRIMARY KEY ID_IMPUESTO TAG ID_IMPUEST COLLATE 'MACHINE'
INDEX ON ID_BIEN TAG ID_BIEN COLLATE 'MACHINE'
INDEX ON NRO_CONTRIBUYENTE TAG NRO_CONTRI COLLATE 'MACHINE'
INDEX ON RECIBO TAG RECIBO COLLATE 'MACHINE'

***** Change properties for IMPUESTOS *****
	STRTOFILE("Table ' IMPUESTOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' IMPUESTOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_RECIBOS
TRY 
***** Table setup for RECIBOS *****
CREATE TABLE 'RECIBOS.DBF' NAME 'RECIBOS' (ID_RECIBO I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                      MONTO_TOTAL N(10, 4) NOT NULL, ;
                      MONTO_IMPUESTO N(10, 4) NOT NULL, ;
                      INTERESES N(10, 4) NOT NULL, ;
                      FECHA_PAGO T NOT NULL)

***** Create each index for RECIBOS *****
ALTER TABLE 'RECIBOS' ADD PRIMARY KEY ID_RECIBO TAG ID_RECIBO COLLATE 'MACHINE'

***** Change properties for RECIBOS *****
	STRTOFILE("Table ' RECIBOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' RECIBOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_PLANES_DE_PAGOS
TRY 
***** Table setup for PLANES_DE_PAGOS *****
CREATE TABLE 'PLANES_DE_PAGOS.DBF' NAME 'PLANES_DE_PAGOS' (ID_PLAN_DE_PAGOS I NOT NULL AUTOINC NEXTVALUE 1 STEP 1, ;
                              NRO_CONTRIBUYENTE I NOT NULL, ;
                              MONTO_TOTAL N(10, 4) NOT NULL, ;
                              CANT_CUOTAS I NOT NULL)

***** Create each index for PLANES_DE_PAGOS *****
ALTER TABLE 'PLANES_DE_PAGOS' ADD PRIMARY KEY ID_PLAN_DE_PAGOS TAG ID_PLAN_DE COLLATE 'MACHINE'
INDEX ON NRO_CONTRIBUYENTE TAG NRO_CONTRI COLLATE 'MACHINE'

***** Change properties for PLANES_DE_PAGOS *****
	STRTOFILE("Table ' PLANES_DE_PAGOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' PLANES_DE_PAGOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_DETALLES_PLAN_DE_PAGOS
TRY 
***** Table setup for DETALLES_PLAN_DE_PAGOS *****
CREATE TABLE 'DETALLES_PLAN_DE_PAGOS.DBF' NAME 'DETALLES_PLAN_DE_PAGOS' (ID_PLAN_DE_PAGOS I NOT NULL, ;
                                     NRO_CUOTA I NOT NULL, ;
                                     MONTO N(10, 4) NOT NULL, ;
                                     FECHA_INICIO D NOT NULL, ;
                                     FECHA_VENCIMIENTO D NOT NULL, ;
                                     RECIBO I NULL)

***** Create each index for DETALLES_PLAN_DE_PAGOS *****
INDEX ON ID_PLAN_DE_PAGOS TAG ID_PLAN_DE COLLATE 'MACHINE'
ALTER TABLE 'DETALLES_PLAN_DE_PAGOS' ADD PRIMARY KEY STR(ID_PLAN_DE_PAGOS)+STR(NRO_CUOTA) TAG ID_DETALLE COLLATE 'MACHINE'
INDEX ON RECIBO TAG RECIBO COLLATE 'MACHINE'

***** Change properties for DETALLES_PLAN_DE_PAGOS *****
	STRTOFILE("Table ' DETALLES_PLAN_DE_PAGOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' DETALLES_PLAN_DE_PAGOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_IMPUESTOXPLAN_DE_PAGOS
TRY 
***** Table setup for IMPUESTOXPLAN_DE_PAGOS *****
CREATE TABLE 'IMPUESTOXPLAN_DE_PAGOS.DBF' NAME 'IMPUESTOXPLAN_DE_PAGOS' (ID_PLAN_DE_PAGOS I NOT NULL, ;
                                     ID_IMPUESTO I NOT NULL)

***** Create each index for IMPUESTOXPLAN_DE_PAGOS *****
ALTER TABLE 'IMPUESTOXPLAN_DE_PAGOS' ADD PRIMARY KEY STR(ID_PLAN_DE_PAGOS)+STR(ID_IMPUESTO) TAG IMPXPDP COLLATE 'MACHINE'
INDEX ON ID_IMPUESTO TAG ID_IMPUEST COLLATE 'MACHINE'
INDEX ON ID_PLAN_DE_PAGOS TAG ID_PLAN_DE COLLATE 'MACHINE'

***** Change properties for IMPUESTOXPLAN_DE_PAGOS *****
	STRTOFILE("Table ' IMPUESTOXPLAN_DE_PAGOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' IMPUESTOXPLAN_DE_PAGOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_CALLES
TRY 
***** Table setup for CALLES *****
CREATE TABLE 'CALLES.DBF' NAME 'CALLES' (DOMICILIO C(50) NOT NULL)

***** Create each index for CALLES *****
INDEX ON DOMICILIO TAG DOMICILIO FOR .NOT.DELETED() CANDIDATE COLLATE 'MACHINE'

***** Change properties for CALLES *****
	STRTOFILE("Table ' CALLES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' CALLES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_LOCALIDADES
TRY 
***** Table setup for LOCALIDADES *****
CREATE TABLE 'LOCALIDADES.DBF' NAME 'LOCALIDADES' (LOCALIDAD C(30) NOT NULL)

***** Create each index for LOCALIDADES *****
INDEX ON LOCALIDAD TAG LOCALIDAD FOR .NOT.DELETED() CANDIDATE COLLATE 'MACHINE'

***** Change properties for LOCALIDADES *****
	STRTOFILE("Table ' LOCALIDADES.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' LOCALIDADES.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_PARTNAC
TRY 
***** Table setup for PARTNAC *****
CREATE TABLE 'PARTNAC.DBF' NAME 'PARTNAC' (ID I NOT NULL AUTOINC NEXTVALUE 2 STEP 1, ;
                      DNI N(10, 0) NOT NULL, ;
                      TOMO N(3, 0) NOT NULL, ;
                      ACTA N(3, 0) NOT NULL, ;
                      AÑO N(4, 0) NOT NULL, ;
                      FECHAINSC D NOT NULL, ;
                      NOMBRE C(50) NOT NULL, ;
                      APELLIDO C(50) NOT NULL, ;
                      SEXO C(1) NOT NULL, ;
                      NACIOLOC C(30) NOT NULL, ;
                      NACIODPTO C(40) NOT NULL, ;
                      MATERNIDAD C(40) NOT NULL, ;
                      NACIOPROV C(25) NOT NULL, ;
                      NACIOHORA C(5) NOT NULL, ;
                      NACIOFECHA D NOT NULL, ;
                      PADRE C(50) NOT NULL, ;
                      PDNI C(10) NOT NULL, ;
                      PNUMDNI N(10, 0) NOT NULL, ;
                      MADRE C(50) NOT NULL, ;
                      MDNI C(10) NOT NULL, ;
                      MNUMDNI N(10, 0) NOT NULL, ;
                      MEDICO C(50) NOT NULL, ;
                      MATRICULA C(20) NOT NULL, ;
                      DECLARANTE C(50) NOT NULL, ;
                      DDNI C(10) NOT NULL, ;
                      DNUMDNI N(10, 0) NOT NULL, ;
                      DOMICILIO C(50) NOT NULL, ;
                      DOMNUM N(5, 0) NOT NULL, ;
                      LOCALIDAD C(30) NOT NULL)

***** Create each index for PARTNAC *****
INDEX ON DNI TAG DNI FOR .NOT.DELETED() CANDIDATE COLLATE 'MACHINE'
INDEX ON ID TAG ID FOR .NOT.DELETED() COLLATE 'MACHINE'

***** Change properties for PARTNAC *****
	STRTOFILE("Table ' PARTNAC.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' PARTNAC.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_DPTOS
TRY 
***** Table setup for DPTOS *****
CREATE TABLE 'DPTOS.DBF' NAME 'DPTOS' (DEPARTAMENTO C(40) NOT NULL)

***** Create each index for DPTOS *****

***** Change properties for DPTOS *****
	STRTOFILE("Table ' DPTOS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' DPTOS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_PROVINCIAS
TRY 
***** Table setup for PROVINCIAS *****
CREATE TABLE 'PROVINCIAS.DBF' NAME 'PROVINCIAS' (PROVINCIA C(25) NOT NULL)

***** Create each index for PROVINCIAS *****
INDEX ON PROVINCIA TAG PROVINCIA FOR .NOT.DELETED() CANDIDATE COLLATE 'MACHINE'

***** Change properties for PROVINCIAS *****
	STRTOFILE("Table ' PROVINCIAS.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' PROVINCIAS.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

FUNCTION MakeTable_TIPODOC
TRY 
***** Table setup for TIPODOC *****
CREATE TABLE 'TIPODOC.DBF' NAME 'TIPODOC' (TIPODOC C(10) NOT NULL)

***** Create each index for TIPODOC *****
INDEX ON TIPODOC TAG TIPODOC FOR .NOT.DELETED() CANDIDATE COLLATE 'MACHINE'

***** Change properties for TIPODOC *****
	STRTOFILE("Table ' TIPODOC.DBF' was created!" + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
CATCH TO loError
	_GenDBC_Error = .T.
	STRTOFILE("***Error while creating ' TIPODOC.DBF', Error: " + loError.Message + CHR(13) + CHR(10), _GenDBC_LogFileName, 1)
ENDTRY

ENDFUNC

*************** Begin Relations Setup **************

FUNCTION MakeRelation_1
ALTER TABLE 'PROPIETARIOS' ADD FOREIGN KEY TAG ID_BIEN REFERENCES CONTRIBUYENTES TAG NRO_CONTRI
ENDFUNC


FUNCTION MakeRelation_2
ALTER TABLE 'PROPIETARIOS' ADD FOREIGN KEY TAG NRO_CONTRI REFERENCES BIENES TAG ID_BIEN
ENDFUNC


FUNCTION MakeRelation_3
ALTER TABLE 'VEHICULOS' ADD FOREIGN KEY TAG ID_BIEN REFERENCES BIENES TAG ID_BIEN
ENDFUNC


FUNCTION MakeRelation_4
ALTER TABLE 'COMERCIOS' ADD FOREIGN KEY TAG ID_BIEN REFERENCES BIENES TAG ID_BIEN
ENDFUNC


FUNCTION MakeRelation_5
ALTER TABLE 'INMUEBLES' ADD FOREIGN KEY TAG ID_BIEN REFERENCES BIENES TAG ID_BIEN
ENDFUNC


FUNCTION MakeRelation_6
ALTER TABLE 'MODELOS' ADD FOREIGN KEY TAG ID_MARCA REFERENCES MARCAS TAG ID_MARCA
ENDFUNC


FUNCTION MakeRelation_7
ALTER TABLE 'INMUEBLES' ADD FOREIGN KEY TAG BARRIO REFERENCES BARRIOS TAG ID_BARRIO
ENDFUNC


FUNCTION MakeRelation_8
ALTER TABLE 'BARRIOS' ADD FOREIGN KEY TAG ID_ZONA REFERENCES BARRIOS TAG ID_BARRIO
ENDFUNC


FUNCTION MakeRelation_9
ALTER TABLE 'BARRIOS' ADD FOREIGN KEY TAG ID_ZONA REFERENCES ZONAS TAG ID_ZONA
ENDFUNC


FUNCTION MakeRelation_10
ALTER TABLE 'IMPUESTOS' ADD FOREIGN KEY TAG NRO_CONTRI REFERENCES CONTRIBUYENTES TAG NRO_CONTRI
ENDFUNC


FUNCTION MakeRelation_11
ALTER TABLE 'IMPUESTOS' ADD FOREIGN KEY TAG ID_BIEN REFERENCES BIENES TAG ID_BIEN
ENDFUNC


FUNCTION MakeRelation_12
ALTER TABLE 'IMPUESTOS' ADD FOREIGN KEY TAG RECIBO REFERENCES RECIBOS TAG ID_RECIBO
ENDFUNC


FUNCTION MakeRelation_13
ALTER TABLE 'DETALLES_PLAN_DE_PAGOS' ADD FOREIGN KEY TAG RECIBO REFERENCES RECIBOS TAG ID_RECIBO
ENDFUNC


FUNCTION MakeRelation_14
ALTER TABLE 'DETALLES_PLAN_DE_PAGOS' ADD FOREIGN KEY TAG ID_PLAN_DE REFERENCES PLANES_DE_PAGOS TAG ID_PLAN_DE
ENDFUNC


FUNCTION MakeRelation_15
ALTER TABLE 'IMPUESTOXPLAN_DE_PAGOS' ADD FOREIGN KEY TAG ID_IMPUEST REFERENCES IMPUESTOS TAG ID_IMPUEST
ENDFUNC


FUNCTION MakeRelation_16
ALTER TABLE 'IMPUESTOXPLAN_DE_PAGOS' ADD FOREIGN KEY TAG ID_PLAN_DE REFERENCES PLANES_DE_PAGOS TAG ID_PLAN_DE
ENDFUNC


FUNCTION DisplayStatus(lcMessage)
*WAIT WINDOW NOWAIT lcMessage
ENDFUNC
