#DEFINE LISTENER_TYPE_PRN     0
#DEFINE LISTENER_TYPE_PAGED   2

#DEFINE VFPSTARTMODE_DEV        1
#DEFINE VFPSTARTMODE_COMEXE     2
#DEFINE VFPSTARTMODE_INPROCDLL  3
#DEFINE VFPSTARTMODE_DISTAPPEXE 4
#DEFINE VFPSTARTMODE_MTDLL      5
#DEFINE VFP_USER_DEFINED_ERROR  1098